# Generated by Django 6.0.6 on 2026-06-30 13:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPaypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('paypal_capture_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('paypal_webhook_event_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('status', models.CharField(choices=[('created', 'Créée'), ('approved', 'Approuvée'), ('captured', 'Payée'), ('failed', 'Échouée'), ('refunded', 'Remboursée')], editable=False, max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(choices=[('francs', 'Francs CFA'), ('euros', 'EUROS'), ('dollars', 'DOLLARS AMERiCAINS')], editable=False, max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_capture', models.DateTimeField(default=datetime.datetime.now)),
                ('reponse_complete', models.JSONField()),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='commande.commande')),
            ],
        ),
    ]
