# Generated by Django 6.0.6 on 2026-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpaypal',
            name='montant',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionpaypal',
            name='reponse_complete',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
