# Generated by Django 6.0.6 on 2026-07-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_alter_commande_reference_alter_commande_utilisateur_and_more'),
        ('paiement', '0002_alter_transactionpaypal_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpaypal',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commande_transaction', to='commande.commande'),
        ),
    ]
