# Generated by Django 6.0.6 on 2026-06-30 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0003_alter_livre_prix_formatlivre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('date_de_commande', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(choices=[('francs', 'Francs CFA'), ('euros', 'EUROS'), ('dollars', 'DOLLARS AMERiCAINS')], default='francs', max_length=10)),
                ('status', models.CharField(choices=[('en_attente', 'Paiement en attente'), ('paye', 'Paiement fait'), ('echec', 'Ecehc de la commande')], default='en_attente', max_length=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'Format PDF'), ('epub', 'Format EPUB')], max_length=5)),
                ('prix_actuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.commande')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.livre')),
            ],
        ),
        migrations.CreateModel(
            name='LienTelechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('format', models.CharField(choices=[('pdf', 'Format PDF'), ('epub', 'Format EPUB')], max_length=5)),
                ('nombre_telechargements', models.PositiveSmallIntegerField(default=0)),
                ('max_telechargements', models.PositiveSmallIntegerField(default=3)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.lignedecommande')),
            ],
        ),
    ]
