# Generated by Django 6.0.6 on 2026-07-01 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_rename_taile_fichier_en_mo_formatlivre_taille_fichier_en_mo_and_more'),
        ('commande', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateur_commande', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lientelechargement',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_lien', to='commande.lignedecommande'),
        ),
        migrations.AlterField(
            model_name='lignedecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='commande.commande'),
        ),
        migrations.AlterField(
            model_name='lignedecommande',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livre_ligne', to='catalogue.livre'),
        ),
    ]
