# Generated by Django 6.0.6 on 2026-06-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('biographie', models.TextField(blank=True)),
                ('pays', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('titre', models.CharField(max_length=300)),
                ('isbn_numerique', models.CharField(blank=True, max_length=20)),
                ('prix', models.PositiveIntegerField()),
                ('langue', models.CharField(max_length=20)),
                ('date_publication', models.DateField(blank=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nombre_ventes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('publie', 'Livre Publié'), ('brouillon', 'Brouillon'), ('archive', 'Une archive')], max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categorie')),
            ],
        ),
    ]
