# Generated by Django 6.0.6 on 2026-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='slug',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
