# Generated by Django 6.0.6 on 2026-06-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_livre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='FormatLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'Format PDF'), ('epub', 'Format EPUB')], max_length=5)),
                ('chemin_fichier', models.URLField()),
                ('taile_fichier_en_mo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.livre')),
            ],
        ),
    ]
