# Generated by Django 6.0.6 on 2026-07-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_livre_prix_formatlivre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formatlivre',
            old_name='taile_fichier_en_mo',
            new_name='taille_fichier_en_mo',
        ),
        migrations.AlterField(
            model_name='formatlivre',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livre_format', to='catalogue.livre'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie', to='catalogue.categorie'),
        ),
    ]
