# Generated by Django 6.0.6 on 2026-07-01 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_rename_taile_fichier_en_mo_formatlivre_taille_fichier_en_mo_and_more'),
        ('panier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livre_article', to='catalogue.livre'),
        ),
        migrations.AlterField(
            model_name='article',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='panier.panier'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
